version: "3.8"

services:
  next-app:
    build:
      context: .
    container_name: next-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app # 로컬 디렉토리를 컨테이너에 마운트
      - /app/node_modules # 컨테이너의 node_modules를 로컬과 분리
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your_secret_key
      - MONGODB_URI=mongodb://mongo:27017/your_db
    depends_on:
      - mongo
    command: npm run dev # 개발 서버 실행 명령어로 변경

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
