services:
  app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/src/app 
    command: ["npm", "run", "dev"]
